# Generated by Django 3.0.5 on 2021-07-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.IntegerField()),
                ('coursename', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trainer', models.CharField(max_length=30)),
                ('sortdesc', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('video', models.CharField(max_length=200)),
                ('button', models.CharField(max_length=200)),
                ('fulldesc', models.CharField(max_length=1000)),
            ],
        ),
    ]
